trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

#variables:
#- name: PRISMA_API_URL
#  value: https://api.prismacloud.io

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'pipeline-connection'
    keyVaultName: 'ts-pipeline-vault'
    secretsFilter: '*'
    runAsPreJob: false
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d . --bc-api-key $(prisma-access-key)::$(prisma-secret-key) --repo-id prismaiac/bicepgoat --branch main
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api.prismacloud.io