trigger:
- main

pr:
- main
 

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- script: |
    echo "Running Checkov Scan!"
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt install python3-pip
    sudo apt-get install python3-testresources
    sudo python3.7 -m pip install botocore==1.20.112
    sudo python3.7 -m pip install -U checkov
    checkov -d .
  displayName: 'IaC code scan using Checkov'
